apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest
  labels:
    app: ingest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingest
  template:
    metadata:
      labels:
        app: ingest
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: my-app
        image: amishra11j/amishra-repo:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
